#!/usr/bin/bash

START=$(cat /tmp/pomodoro)
COLORBG_ACTIVE="#5DADE2"
COLORBG_ACTIVE2="#1B4F72"
COLORBG_INACTIVE="#666666"
COLORBG_INACTIVE2="#333333"

case $BLOCK_BUTTON in
    1)
        echo `date +%s` > /tmp/pomodoro
        echo '<span background="'$COLORBG_ACTIVE2'"> ⏳ </span><span background="'$COLORBG_ACTIVE'" foreground="white"> 0 min </span>'
        ;;
    3)
        rm /tmp/pomodoro
        echo '<span background="'$COLORBG_INACTIVE2'"> 💤 </span><span background="'$COLORBG_INACTIVE'" foreground="white"> Ready... </span>'
esac


if [[ ! -z $START ]]; then
    NOW=$(date +%s)
    SEC_ELAPSED=$((NOW-START))
    MIN_ELAPSED=$((SEC_ELAPSED/60))
    echo '<span background="'$COLORBG_ACTIVE2'"> ⏳ </span><span background="'$COLORBG_ACTIVE'" foreground="white"> '$MIN_ELAPSED' min </span>'
else 
    echo "Ready"
fi
